#define PROJECT_VERSION_MAJOR 0
#define PROJECT_VERSION_MINOR 0
#define PROJECT_VERSION_PATCH 1

#define PROJECT_VERSION "0.0.1"

#define PROJECT_GIT_BRANCH "feat/stacktrace"

#define PROJECT_CXX_COMPILER "GNU"
#define PROJECT_CXX_COMPILER_VERSION "13.2.1"

#define PROJECT_COMPILE_DATE "Jun 09 2024"
#define PROJECT_COMPILE_TIME "14:13:04"

#define CMAKE_HOST_SYSTEM_NAME "Linux"
